apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-flask-backend-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: rest-flask-backend-app
  replicas: 1
  template:
    metadata:
      labels:
        app: rest-flask-backend-app
    spec:
      containers:
      - name: flask
        image: 434692986520.dkr.ecr.us-west-2.amazonaws.com/hanggi-ecr:v1.0.0
        env:
          - name: REDIS_HOST
            valueFrom:
              configMapKeyRef:
                name: backend
                key: REDIS_HOST
        ports:
        - containerPort: 5000
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rest-flask-backend-deployment
  name: rest-flask-backend-service
  namespace: default
spec:
  type: ClusterIP
  ports:
  - port: 8080
  selector:
    app: rest-flask-backend-deployment
